server:
  port: 8086

app:
  mail:
    enabled: ${APP_MAIL_ENABLED:true}

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/locadora_rdt
    username: postgres
    password: root

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

    properties:
      hibernate:
        format_sql: true
